language: ruby
rvm:
- 2.4.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure:     XA02zLo325Z35JnFWhufpA76PdOvaefQZ8Nyt2FnNU9zPg15motDYjrioF3tY+5xaDrvZgkGDfWjRbuIgpTU1j2C8JxpbGTox02uxYryi92Wdmv1U3rn2GHroLkWfq4Ur2pbfx5Zz/h3Nl91Bp0FZnyLR4SklnqhXVNfZY20jDrzYM1Df9OHNaE7FgWjK+Ws3dDgjTbNU10sFJptBkFIKKamRmjH0SqjgjU3WwX4AFbS+TKbyHNoT3MQ8SQyPNF+WWvz4ZyOfdETDHO5eHcIHcb4QLXssQI4wv5vi01LY9MQtyksEvqy3SBCYBtg3rZnK/T6rVTafvHNLq/B8XpbHc4h5isJKvy5j3/pgG5iWoA4py0Y10LU637ErADBH69v0ueS+gE9tKRHRBfmx2aVJL6j7GzFXveCfe1M/8V46ewjSRkU2UOcwNXnxVfbUAgmB9393aCyBT3rlvhAKStIUuJOH8acF3YfJoW9M1lgb/qk3bx3F3KbgXe8DVyRYKGwBrLLO2a/5aa3N7VCli/WCy9fApz4PG4Q0ZzPXaTe1WvsdxS8NKIGblK0kgyYca/GVuQepobJqNd0ibRws2yWazc4RXLQ8QJYf/HJC/42pav0vmBtCJLHbdDotct4S+mcmOy2gUsEW8OKzUqy4UXfOUU92XYhumfi1iXJtro2aeU=
  app:
    develop: my-rails-project-staging
    master: my-rails-project-production
  on:
    repo: tochman/my_new_rails_project
  run:
    - "rails db:migrate"
